- __NOTE__ I'm lazy so I'm going to use list comphrensions to write some of the "boiler plate" code
    - also _note_ some absue of the print() functon












- And just to keep things clean

```

pandas.__version__

'1.0.3'


```

In [3]:
import pandas as pd

- Loading data

_path from current location:_

```
"../Datasets/UCR/IMPD_UCR/"
```

In [7]:
uof_all_read  = pd.read_csv("../CleanedDataFromDec19/UOF/UOF_all___with_lat_lon_and_zip_up_to_dec_2019.csv")

In [8]:
uof_all = uof_all_read.copy()

In [9]:
uof_all.columns

Index(['zip', 'latitude', 'longitude', 'INCNUM', 'OBJECTID', 'YMD_TM',
       'OCCURRED_DT', 'OCCURRED_TM', 'UDTEXT24A', 'UDTEXT24B', 'UDTEXT24C',
       'UDTEXT24D', 'DISPOSITION', 'STREET_N', 'STREET', 'STREET_T',
       'STREET_G', 'CITY', 'UOF_FORCE_TYPE', 'UOF_REASON', 'SERVICE_TYPE',
       'CIT_ARRESTED', 'CITCHARGE_TYPE', 'CIT_WEAPON_TYPE', 'CIT_INJURED',
       'CIT_HOSPITAL', 'OFF_INJURED', 'OFF_HOSPITAL', 'CIT_NUM', 'CIT_RACE',
       'CIT_SEX', 'CIT_AGE', 'CIT_COND_TYPE', 'OFF_NUM', 'OFF_RACE', 'OFF_SEX',
       'OFF_AGE', 'OFF_YR_EMPLOY', 'OFF_COND_TYPE', 'STATE',
       'OCCURRED_WEEK_DAY', 'OCCURRED_HOUR', 'OCCURRED_QUARTER',
       'OCCURRED_YEAR', 'lat', 'lon'],
      dtype='object')

In [10]:
# kinda pointless at this stage
uof_all.describe()

,latitude,longitude,INCNUM,OBJECTID,STREET_N,CIT_NUM,CIT_AGE,OFF_NUM,OFF_AGE,OFF_YR_EMPLOY,OCCURRED_HOUR,OCCURRED_QUARTER,OCCURRED_YEAR,lat,lon
count,70764.000000,70764.000000,73083.000000,73080.000000,72888.000000,73080.000000,73080.000000,73080.00000,73080.000000,73080.000000,71936.000000,71936.000000,71936.000000,70764.000000,70764.000000
mean,39.785574,-86.144130,25842.022947,36534.680378,3194.107754,13783.609811,53833.225807,6732.51356,55411.047222,7.464409,12.214482,2.558079,2017.414202,39.785574,-86.144130
std,0.057035,0.277243,10360.846388,21096.220163,2489.204632,6285.321077,225624.963478,63457.66439,228709.183039,7.250731,7.784279,1.077309,1.413105,0.057035,0.277243
min,39.528900,-87.646050,156.000000,1.000000,1.000000,1.000000,4.000000,3.00000,21.000000,0.000000,0.000000,1.000000,2014.000000,39.528900,-87.646050
25%,39.760589,-86.208489,18218.000000,18264.750000,1066.000000,8866.000000,23.000000,2113.00000,30.000000,2.000000,3.000000,2.000000,2016.000000,39.760589,-86.208489
50%,39.781348,-86.152640,26853.000000,36534.500000,2919.000000,14309.000000,30.000000,3071.00000,34.000000,5.000000,15.000000,3.000000,2018.000000,39.781348,-86.152640
75%,39.817315,-86.105471,34240.000000,54804.250000,4545.000000,19152.000000,39.000000,3382.00000,42.000000,12.000000,19.000000,3.000000,2019.000000,39.817315,-86.105471
max,41.834501,-73.971249,43123.000000,73074.000000,19725.000000,23532.000000,999999.000000,999999.00000,999999.000000,46.000000,23.000000,4.000000,2019.000000,41.834501,-73.971249

In [12]:
uof_all.isnull().sum()

zip                   2323
latitude              2319
longitude             2319
INCNUM                   0
OBJECTID                 3
YMD_TM                1147
OCCURRED_DT             13
OCCURRED_TM           1143
UDTEXT24A                3
UDTEXT24B                3
UDTEXT24C                3
UDTEXT24D                3
DISPOSITION              3
STREET_N               195
STREET                  96
STREET_T              1486
STREET_G             20976
CITY                    96
UOF_FORCE_TYPE           3
UOF_REASON               3
SERVICE_TYPE             3
CIT_ARRESTED             3
CITCHARGE_TYPE           3
CIT_WEAPON_TYPE          3
CIT_INJURED              3
CIT_HOSPITAL             3
OFF_INJURED              3
OFF_HOSPITAL             3
CIT_NUM                  3
CIT_RACE                 3
CIT_SEX                  3
CIT_AGE                  3
CIT_COND_TYPE            3
OFF_NUM                  3
OFF_RACE                 3
OFF_SEX                  3
OFF_AGE                  3
OFF_YR_EMPLOY            3
OFF_COND_TYPE            3
STATE                    3
OCCURRED_WEEK_DAY       13
OCCURRED_HOUR         1147
OCCURRED_QUARTER      1147
OCCURRED_YEAR         1147
lat                   2319
lon                   2319
dtype: int64

In [16]:
uof_all['YEARLY_COUNT'] = uof_all.groupby('OCCURRED_YEAR')['OCCURRED_YEAR'].transform('count')

In [24]:
uof_all

,zip,latitude,longitude,INCNUM,OBJECTID,YMD_TM,OCCURRED_DT,OCCURRED_TM,UDTEXT24A,UDTEXT24B,...,OFF_YR_EMPLOY,OFF_COND_TYPE,STATE,OCCURRED_WEEK_DAY,OCCURRED_HOUR,OCCURRED_QUARTER,OCCURRED_YEAR,lat,lon,YEARLY_COUNT
0,46254,39.838112,-86.244154,34144,1001.0,2019-02-14T20:01:00Z,2019-02-14,20:01:00:000,OPERATIONS DIVISION,NORTHWEST DISTRICT,...,2.0,NO INJURIES NOTED OR VISIBLE,IN,Thu,20.0,1.0,2019.0,39.838112,-86.244154,20779.0
1,46254,39.838112,-86.244154,34144,778.0,2019-02-14T20:01:00Z,2019-02-14,20:01:00:000,OPERATIONS DIVISION,NORTHWEST DISTRICT,...,2.0,MINOR SCRAPES,IN,Thu,20.0,1.0,2019.0,39.838112,-86.244154,20779.0
2,46254,39.838112,-86.244154,34144,779.0,2019-02-14T20:01:00Z,2019-02-14,20:01:00:000,OPERATIONS DIVISION,NORTHWEST DISTRICT,...,2.0,BRUISING,IN,Thu,20.0,1.0,2019.0,39.838112,-86.244154,20779.0
3,46254,39.838112,-86.244154,34144,780.0,2019-02-14T20:01:00Z,2019-02-14,20:01:00:000,OPERATIONS DIVISION,NORTHWEST DISTRICT,...,2.0,MINOR SCRAPES,IN,Thu,20.0,1.0,2019.0,39.838112,-86.244154,20779.0
4,46254,39.838112,-86.244154,34144,781.0,2019-02-14T20:01:00Z,2019-02-14,20:01:00:000,OPERATIONS DIVISION,NORTHWEST DISTRICT,...,2.0,BRUISING,IN,Thu,20.0,1.0,2019.0,39.838112,-86.244154,20779.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73078,NaN,NaN,NaN,38557,67379.0,2019-06-30T00:48:00Z,2019-06-30,00:48:00:000,OPERATIONS DIVISION,SOUTHWEST DISTRICT,...,0.0,NO INJURIES NOTED OR VISIBLE,IN,Sun,0.0,2.0,2019.0,NaN,NaN,20779.0
73079,NaN,NaN,NaN,38557,67380.0,2019-06-30T00:48:00Z,2019-06-30,00:48:00:000,OPERATIONS DIVISION,SOUTHWEST DISTRICT,...,0.0,NO INJURIES NOTED OR VISIBLE,IN,Sun,0.0,2.0,2019.0,NaN,NaN,20779.0
73080,NaN,NaN,NaN,39070,66393.0,2019-07-25T18:00:00Z,2019-07-25,18:00:00:000,ADMINISTRATION DIVISION,TRAINING BUREAU,...,0.0,NO INJURIES NOTED OR VISIBLE,IN,Thu,18.0,3.0,2019.0,NaN,NaN,20779.0
73081,NaN,NaN,NaN,39070,66394.0,2019-07-25T18:00:00Z,2019-07-25,18:00:00:000,ADMINISTRATION DIVISION,TRAINING BUREAU,...,3.0,NO INJURIES NOTED OR VISIBLE,IN,Thu,18.0,3.0,2019.0,NaN,NaN,20779.0
73082,NaN,NaN,NaN,39070,66395.0,2019-07-25T18:00:00Z,2019-07-25,18:00:00:000,ADMINISTRATION DIVISION,TRAINING BUREAU,...,3.0,NO INJURIES NOTED OR VISIBLE,IN,Thu,18.0,3.0,2019.0,NaN,NaN,20779.0

In [23]:
X = uof_all['YEARLY_COUNT', 'OCURRED_YEAR']

KeyError: ('YEARLY_COUNT', 'OCURRED_YEAR')

In [35]:
df['ABBR_CRIME'] = df['CRIME'].astype(str) + " - "

In [36]:
df['ABBR_CRIME'] = df['ABBR_CRIME'].str.replace(pat="\- ATTEMPT", 
                                                repl="ATTEMPT- ") # ensuring the "attempted" crimes are kept since they were not perpetuated
df['ABBR_CRIME'] = df['ABBR_CRIME'].str.split('-').str.get(0) # turning column into a list of strings, then returning only the first item in the list
df['ABBR_CRIME'] = df['ABBR_CRIME'].str.strip() # removing excess white space

- Making a factor of the abbreviated crimes
    - Which also doubles as a way to narrow down the "root" of the crimes, which will make it easier to graph

In [37]:
factored_abbreviated_crime = df['ABBR_CRIME'].unique()
sorted(factored_abbreviated_crime)

['AGGRAVATED ASSAULT',
 'ASSAULT',
 'ATTEMPT ARMED ROBBERY',
 'ATTEMPT STRONG ARMED ROBBER',
 'ATTEMPT STRONG ARMED ROBBERY',
 'ATTEMPT VEHICLE THEFT',
 'BURG',
 'CRIMINAL HOMICIDE',
 'LARC',
 'LARCENY',
 'LARCENY ATTEMPT',
 'MANSLAUGHTER BY NEG',
 'RAPE',
 'RAPE ATTEMPT',
 'ROBBERY',
 'ROBBERY ATTEMPT',
 'STOLEN VEHICLE',
 'VEHICLE THEFT',
 'VEHICLE THEFT ATTEMPT']

In [38]:
df['ABBR_CRIME'] = df['ABBR_CRIME'].replace(['LARC', 'AB'], 'LARCENY')


df['ABBR_CRIME'] = df['ABBR_CRIME'].replace(["BURG", "BURGLARY"],
                                                "BURGLARY")

df['ABBR_CRIME'] = df['ABBR_CRIME'].replace(["ATTEMPT STRONG ARMED ROBBER", "ATTEMPT ARMED ROBBERY", "ATTEMPT STRONG ARMED ROBBERY"], 
                                            "ROBBERY ATTEMPT")

df['ABBR_CRIME'] = df['ABBR_CRIME'].str.replace(pat="ATTEMPT VEHICLE THEFT", 
                                                repl="VEHICLE THEFT ATTEMPT")


df['ABBR_CRIME'] = df['ABBR_CRIME'].str.replace(pat="STOLEN VEHICLE", 
                                                repl="VEHICLE THEFT")

df['ABBR_CRIME'] = df['ABBR_CRIME'].str.replace(pat="AGGRAVATED ASSAULT", 
                                                repl="ASSAULT")

df['ABBR_CRIME'] = df['ABBR_CRIME'].str.replace(pat="MANSLAUGHTER BY NEG", 
                                                repl="MANSLAUGHTER BY NEGLEGENCE")

In [39]:
factored_abbreviated_crime = df['ABBR_CRIME'].unique()
sorted(factored_abbreviated_crime)

['ASSAULT',
 'BURGLARY',
 'CRIMINAL HOMICIDE',
 'LARCENY',
 'LARCENY ATTEMPT',
 'MANSLAUGHTER BY NEGLEGENCE',
 'RAPE',
 'RAPE ATTEMPT',
 'ROBBERY',
 'ROBBERY ATTEMPT',
 'VEHICLE THEFT',
 'VEHICLE THEFT ATTEMPT']

In [40]:
len(factored_abbreviated_crime)

12

In [126]:
df

,OBJECTID,UCR,CRIME,DATE_,TIME,CASE,ADDRESS,BEAT,X_COORD,Y_COORD,YMD,YEAR,MONTH,DAY,WEEKDAY,ABBR_CRIME
0,1001,133,ROBBERY - ATTEMPT STRARM,2007-03-21 00:00:00+00:00,20:30,070040361I,02200 N MERIDIAN ST,NW13,190236.37,1657266.05,2007-03-21,2007,3,21,Wed,ROBBERY ATTEMPT
1,1002,133,ROBBERY - ATTEMPT STRARM,2007-03-24 00:00:00+00:00,12:53,070041855I,05630 FLIGHT SCHOOL DR,SW72,161402.77,1621638.94,2007-03-24,2007,3,24,Sat,ROBBERY ATTEMPT
2,1003,133,ROBBERY - ATTEMPT STRARM,2007-03-24 00:00:00+00:00,23:29,070042125I,05349 W PIKE PLAZA RD,NW33,163351.68,1669325.90,2007-03-24,2007,3,24,Sat,ROBBERY ATTEMPT
3,1004,133,ROBBERY - ATTEMPT STRARM,2007-03-25 00:00:00+00:00,04:05,070042251I,00200 SPICEWOOD DR,SE31,191124.92,1626135.34,2007-03-25,2007,3,25,Sun,ROBBERY ATTEMPT
4,1005,133,ROBBERY - ATTEMPT STRARM,2007-03-25 00:00:00+00:00,18:01,070000517I,11351 E WASHINGTON ST,NE63,244320.27,1649255.47,2007-03-25,2007,3,25,Sun,ROBBERY ATTEMPT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750723,129191,258,LARCENY-UNDER 50-OTHER,2019-01-11 00:00:00+00:00,13:00,I190004039A,2810 DR ANDREW J BROWN AVE,NE12,196230.57,1660874.61,2019-01-11,2019,1,11,Fri,LARCENY
750724,129192,258,LARCENY-UNDER 50-OTHER,2019-01-11 00:00:00+00:00,17:16,I190004106A,222 OHMER AVE,NE42,212277.20,1645989.05,2019-01-11,2019,1,11,Fri,LARCENY
750725,129193,258,LARCENY-UNDER 50-OTHER,2019-01-12 00:00:00+00:00,15:00,I190005609A,645 N TEMPLE AVE,NE22,200991.29,1649956.68,2019-01-12,2019,1,12,Sat,LARCENY
750726,129194,258,LARCENY-UNDER 50-OTHER,2019-01-12 00:00:00+00:00,00:00,I190006119A,901 FORT WAYNE AVE,DT21,191875.35,1650568.75,2019-01-12,2019,1,12,Sat,LARCENY
750727,129195,258,LARCENY-UNDER 50-OTHER,2019-01-13 00:00:00+00:00,11:45,I190004551A,6500 E WASHINGTON ST,NE42,218623.90,1647752.48,2019-01-13,2019,1,13,Sun,LARCENY

In [140]:
def convertYtoLat(y):
    return (47 + (y / 6096 / 60))

In [141]:
def convartXtoLon(x):
    import math
    return (-117.2 - (x / (6096 * math.cos(47.58)) / 60))

In [142]:
y = df.copy()

In [146]:
convartXtoLon(y['X_COORD'][1])

-116.70847180415454

In [145]:
convertYtoLat(y['Y_COORD'][1])

51.433614774715664

In [ ]:
-116.70847180415454, 51.433614774715664

In [149]:
import pyproj
import math

P = pyproj.Proj(proj='utm', zone=31, ellps='WGS84', preserve_units=True)
G = pyproj.Geod(ellps='WGS84')

In [152]:
help(pyproj.Proj)

Help on class Proj in module pyproj.proj:

class Proj(pyproj._proj._Proj)
 |  Performs cartographic transformations (converts from
 |  longitude,latitude to native map projection x,y coordinates and
 |  vice versa) using PROJ (https://proj.org).
 |
 |  A Proj class instance is initialized with proj map projection
 |  control parameter key/value pairs. The key/value pairs can
 |  either be passed in a dictionary, or as keyword arguments,
 |  or as a PROJ string (compatible with the proj command). See
 |  https://proj.org/operations/projections/index.html for examples of
 |  key/value pairs defining different map projections.
 |
 |  Calling a Proj class instance with the arguments lon, lat will
 |  convert lon/lat (in degrees) to x/y native map projection
 |  coordinates (in meters).  If optional keyword 'inverse' is True
 |  (default is False), the inverse transformation from x/y to
 |  lon/lat is performed. If optional keyword 'errcheck' is True (default is
 |  False) an exception is raised if the transformation is invalid.
 |  If errcheck=False and the transformation is invalid, no
 |  exception is raised and 'inf' is returned. If the optional keyword
 |  'preserve_units' is True, the units in map projection coordinates
 |  are not forced to be meters.
 |
 |  Works with numpy and regular python array objects, python
 |  sequences and scalars.
 |
 |  Attributes
 |  ----------
 |  srs: str
 |      The string form of the user input used to create the Proj.
 |  crs: pyproj.crs.CRS
 |      The CRS object associated with the Proj.
 |
 |  Method resolution order:
 |      Proj
 |      pyproj._proj._Proj
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __call__(self, *args, **kw) -> Tuple[Any, Any]
 |      Calling a Proj class instance with the arguments lon, lat will
 |      convert lon/lat (in degrees) to x/y native map projection
 |      coordinates (in meters).  If optional keyword 'inverse' is True
 |      (default is False), the inverse transformation from x/y to
 |      lon/lat is performed. If optional keyword 'errcheck' is True (default is
 |      False) an exception is raised if the transformation is invalid.
 |      If errcheck=False and the transformation is invalid, no
 |      exception is raised and 'inf' is returned.
 |
 |      Inputs should be doubles (they will be cast to doubles if they
 |      are not, causing a slight performance hit).
 |
 |      Works with numpy and regular python array objects, python
 |      sequences and scalars, but is fastest for array objects.
 |
 |  __eq__(self, other:Any) -> bool
 |      Return self==value.
 |
 |  __init__(self, projparams:Any=None, preserve_units:bool=True, **kwargs) -> None
 |      initialize a Proj class instance.
 |
 |      See the PROJ documentation (https://proj.org)
 |      for more information about projection parameters.
 |
 |      Parameters
 |      ----------
 |      projparams: int, str, dict, pyproj.CRS
 |          A PROJ or WKT string, PROJ dict, EPSG integer, or a pyproj.CRS instance.
 |      preserve_units: bool
 |          If false, will ensure +units=m.
 |      **kwargs:
 |          PROJ projection parameters.
 |
 |
 |      Example usage:
 |
 |      >>> from pyproj import Proj
 |      >>> p = Proj(proj='utm',zone=10,ellps='WGS84', preserve_units=False)
 |      >>> x,y = p(-120.108, 34.36116666)
 |      >>> 'x=%9.3f y=%11.3f' % (x,y)
 |      'x=765975.641 y=3805993.134'
 |      >>> 'lon=%8.3f lat=%5.3f' % p(x,y,inverse=True)
 |      'lon=-120.108 lat=34.361'
 |      >>> # do 3 cities at a time in a tuple (Fresno, LA, SF)
 |      >>> lons = (-119.72,-118.40,-122.38)
 |      >>> lats = (36.77, 33.93, 37.62 )
 |      >>> x,y = p(lons, lats)
 |      >>> 'x: %9.3f %9.3f %9.3f' % x
 |      'x: 792763.863 925321.537 554714.301'
 |      >>> 'y: %9.3f %9.3f %9.3f' % y
 |      'y: 4074377.617 3763936.941 4163835.303'
 |      >>> lons, lats = p(x, y, inverse=True) # inverse transform
 |      >>> 'lons: %8.3f %8.3f %8.3f' % lons
 |      'lons: -119.720 -118.400 -122.380'
 |      >>> 'lats: %8.3f %8.3f %8.3f' % lats
 |      'lats:   36.770   33.930   37.620'
 |      >>> p2 = Proj('+proj=utm +zone=10 +ellps=WGS84', preserve_units=False)
 |      >>> x,y = p2(-120.108, 34.36116666)
 |      >>> 'x=%9.3f y=%11.3f' % (x,y)
 |      'x=765975.641 y=3805993.134'
 |      >>> p = Proj("epsg:32667", preserve_units=False)
 |      >>> 'x=%12.3f y=%12.3f (meters)' % p(-114.057222, 51.045)
 |      'x=-1783506.250 y= 6193827.033 (meters)'
 |      >>> p = Proj("epsg:32667")
 |      >>> 'x=%12.3f y=%12.3f (feet)' % p(-114.057222, 51.045)
 |      'x=-5851386.754 y=20320914.191 (feet)'
 |      >>> # test data with radian inputs
 |      >>> p1 = Proj("epsg:4214")
 |      >>> x1, y1 = p1(116.366, 39.867)
 |      >>> '{:.3f} {:.3f}'.format(x1, y1)
 |      '116.366 39.867'
 |      >>> x2, y2 = p1(x1, y1, inverse=True)
 |      >>> '{:.3f} {:.3f}'.format(x2, y2)
 |      '116.366 39.867'
 |
 |  __reduce__(self) -> Tuple[Type[_ForwardRef('Proj')], Tuple[str]]
 |      special method that allows pyproj.Proj instance to be pickled
 |
 |  __repr__(self) -> str
 |      Return repr(self).
 |
 |  definition_string(self) -> str
 |      Returns formal definition string for projection
 |
 |      >>> Proj("epsg:4326").definition_string()
 |      'proj=longlat datum=WGS84 no_defs ellps=WGS84 towgs84=0,0,0'
 |
 |  get_factors(self, longitude:Any, latitude:Any, radians:bool=False, errcheck:bool=False) -> importlib._bootstrap.Factors
 |      .. versionadded:: 2.6.0
 |
 |      Calculate various cartographic properties, such as scale factors, angular
 |      distortion and meridian convergence. Depending on the underlying projection
 |      values will be calculated either numerically (default) or analytically.
 |
 |      The function also calculates the partial derivatives of the given
 |      coordinate.
 |
 |      Parameters
 |      ----------
 |      longitude: scalar or array (numpy or python)
 |          Input longitude coordinate(s).
 |      latitude: scalar or array (numpy or python)
 |          Input latitude coordinate(s).
 |      radians: boolean, optional
 |          If True, will expect input data to be in radians.
 |          Default is False (degrees).
 |      errcheck: boolean, optional (default False)
 |          If True an exception is raised if the errors are found in the process.
 |          By default errcheck=False and ``inf`` is returned.
 |
 |      Returns
 |      -------
 |      Factors
 |
 |  to_latlong(self) -> 'Proj'
 |      return a new Proj instance which is the geographic (lat/lon)
 |      coordinate version of the current projection
 |
 |  to_latlong_def(self) -> Union[str, NoneType]
 |      return the definition string of the geographic (lat/lon)
 |      coordinate version of the current projection
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __hash__ = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pyproj._proj._Proj:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  __setstate__ = __setstate_cython__(...)
 |      _Proj.__setstate_cython__(self, __pyx_state)
 |
 |  is_exact_same(...)
 |      _Proj.is_exact_same(self, other)
 |      Compares Proj objects to see if they are exactly the same.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pyproj._proj._Proj:
 |
 |  definition
 |
 |  has_inverse
 |      Returns true if this projection has an inverse
 |
 |  srs

In [151]:
def LatLon_To_XY(Lat,Lon):
    return P(Lat,Lon)    

def XY_To_LatLon(x,y):
    return P(x,y,inverse=True)    

def distance(Lat1, Lon1, Lat2, Lon2):
    return G.inv(Lon1, Lat1, Lon2, Lat2)[2]

In [155]:
from pyproj import Proj
pnyc = Proj(
     proj='lcc',
     datum='NAD83',
     lat_1=39.768331,
#      lat_2=41.033333,
#      lat_0=40.166667,
     lon_0=-86.583502,
     x_0=984250.0,
     y_0=0.0)
x = [161402.77] # 161402.77 	1621638.94
y = [1621638.94]
lon, lat = pnyc(x, y, inverse=True)
lon, lat

([-94.68502915280463], [14.977974650944603])

In [ ]:
39.7683331, -86.1583502